#!/bin/bash


clear
echo "Settings:"
echo "========="
echo "domain:"
echo $DOMAIN
echo "========="
echo "folder:"
echo $TEST_FOLDER
echo ""
echo "install TEST? (y/n)"
read continue
if [[ $continue = "y" ]]
then


echo "Create directory=============================="
cd
mkdir $TEST_FOLDER
cd $TEST_FOLDER
echo "Created directory============================="


echo "Installing git repository====================="
git clone https://github.com/AlenAlic/clubpromoters-front
cd clubpromoters-front
echo "Installing git repository complete============"


echo "Setting up config============================="
sudo bash -c 'cat > public/config/config.json' << EOL
{
    "cookies": {
        "enabled": true,
        "type": "banner"
    },
    "api": {
        "url": "https://test.api.$DOMAIN"
    }
}
EOL
echo "Setting up config complete===================="


echo "Build frontend================================"
npm install
npm run build
echo "Building complete============================="


echo "Setting up nginx=============================="
sudo -E bash -c 'cat > /etc/nginx/conf.d/test.$DOMAIN.conf' << EOL
server {
    listen 443 ssl http2;
    server_name test.$DOMAIN;

    location / {
        root /home/$USER/$TEST_FOLDER/clubpromoters-front/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    access_log /var/log/test.$DOMAIN.access.log;
    error_log /var/log/test.$DOMAIN.error.log;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

}
server {
    server_name test.$DOMAIN;
    return 301 https://\$host\$request_uri;
}
EOL
sudo service nginx reload
echo "Setting up nginx complete====================="


echo "Creating update script========================"
bash -c 'cat > scripts/update' << EOL
cd clubpromoters-front

echo "Checking out new version===="
git pull
echo "========================Done"

echo "Building frontend==========="
npm install
npm run build
echo "========================Done"

echo "Restarting Services========="
sudo systemctl reload nginx
echo "========================Done"

cd ..
EOL
echo "Created update script========================="



else
echo "Skipping TEST installation."
fi
cd
