#!/bin/bash


clear
export DEMO_FOLDER=demo
export DEMO_FRONT_FOLDER=$DEMO_FOLDER/clubpromoters-front

export DOMAIN=clubpromoters.net
export DEMO_SUBDOMAIN=demo.$DOMAIN
export DEMO_API_SUBDOMAIN=api.$DEMO_SUBDOMAIN;

echo "SETTINGS"
echo "========="
echo "folder:"
echo $DEMO_FOLDER
echo "domain:"
echo $DOMAIN
echo "========="
echo ""

echo "install demo? (y/n)"
read continue
if [[ $continue = "y" ]]
then


echo "Installing git repository====================="
cd
mkdir $DEMO_FOLDER
cd $DEMO_FOLDER
git clone https://github.com/AlenAlic/clubpromoters-front
echo "Installing git repository complete============"


echo "Setting up config============================="
cd && cd $DEMO_FRONT_FOLDER
sudo bash -c 'cat > public/config/config.json' << EOL
{
    "cookies": {
        "enabled": true,
        "type": "banner"
    },
    "api": {
        "url": "https://$DEMO_API_SUBDOMAIN"
    },
    "terms": "https://$DEMO_API_SUBDOMAIN/api/documents/terms",
    "promoter_terms": "https://$DEMO_API_SUBDOMAIN/api/documents/promoter_terms",
}
EOL
echo "Setting up config complete===================="


echo "Build frontend================================"
npm install
npm run build
echo "Building complete============================="


echo "Setting up nginx=============================="
sudo -E bash -c 'cat > /etc/nginx/conf.d/$DEMO_SUBDOMAIN.conf' << EOL
server {
    listen 443 ssl http2;
    server_name $DEMO_SUBDOMAIN;

    location / {
        root /home/$USER/$DEMO_FRONT_FOLDER/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    access_log /var/log/$DEMO_SUBDOMAIN.access.log;
    error_log /var/log/$DEMO_SUBDOMAIN.error.log;

    ssl_certificate /etc/letsencrypt/live/$DEMO_SUBDOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DEMO_SUBDOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

}
server {
    server_name $DEMO_SUBDOMAIN;
    return 301 https://\$host\$request_uri;
}
EOL
sudo service nginx reload
echo "Setting up nginx complete====================="


echo "Creating update script========================"
cd && cd $DEMO_FRONT_FOLDER
bash -c 'cat > scripts/update' << EOL
cd && cd $DEMO_FRONT_FOLDER

echo "Checking out new version===="
git pull
echo "========================Done"

echo "Building frontend==========="
npm install
npm run build
echo "========================Done"

echo "Restarting Services========="
sudo systemctl reload nginx
echo "========================Done"

cd
EOL
echo "Created update script========================="


echo "Creating update scripts======================="
cd
echo "alias demo-front-update='cd && source $DEMO_FRONT_FOLDER/scripts/update'" >> .bashrc
source .bashrc
echo "Created update scripts========================"


else
echo "Skipping DEMO installation."
fi
cd
